language: ruby
rvm: 2.1.2
deploy:
  provider: heroku
  app: configdb-dev
  on:
    repo: stanchino/ConfigDB
    branch: development
  api_key:
    secure: RxopYr4I6SCxLK6eMnTnxmP+mHAGrC1e6eMAUGxchCpuCUAI4Xay/e93smJswaoK2+v5llq6UBIHWGDfr21DwGT/XqKx+WcMtJFmDusdRBVgihkVgWzcwiI7InA9/XUriB0nnedABRMSaQTV7/Q0f7okOEI7qME43MeskUqR/TY=
  run: "rake db:migrate"
  strategy: git
addons:
  code_climate:
    repo_token: a1050d2800de178a7c5dd367f4fbbf29c1ec5597842f912582a0599cd24ea644
env:
  - "NUM_GROUPS=5 GROUP=1"
  - "NUM_GROUPS=5 GROUP=2"
  - "NUM_GROUPS=5 GROUP=3"
  - "NUM_GROUPS=5 GROUP=4"
  - "NUM_GROUPS=5 GROUP=5"
script:
  - bundle exec rake parallel:spec -n $NUM_GROUPS --only-group $GROUP --group-by filesize --type rspec
