language: ruby
rvm: 2.1.2
deploy:
  provider: heroku
  app: configdb-dev
  on:
    repo: stanchino/ConfigDB
    branch: development
  api_key:
    secure: RxopYr4I6SCxLK6eMnTnxmP+mHAGrC1e6eMAUGxchCpuCUAI4Xay/e93smJswaoK2+v5llq6UBIHWGDfr21DwGT/XqKx+WcMtJFmDusdRBVgihkVgWzcwiI7InA9/XUriB0nnedABRMSaQTV7/Q0f7okOEI7qME43MeskUqR/TY=
  run: "rake db:migrate"
  strategy: git
